# Generated by Django 5.2.2 on 2026-08-24 18:18

import apps.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[apps.accounts.validators.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+79\\d{9}$', 'Телефон должен быть в формате +79XXXXXXXXX.')]),
        ),
    ]
