# Generated by Django 5.2.2 on 2026-09-03 16:00

from django.db import migrations, models

from apps.accounts.models import PUBLIC_ID_OFFSET


def backfill_public_id(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(public_id__isnull=True).update(
        public_id=models.F("id") + PUBLIC_ID_OFFSET
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='адрес доставки приза'),
        ),
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(backfill_public_id, noop),
    ]
