# Generated by Django 5.2.2 on 2026-09-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_user_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_consent',
            field=models.BooleanField(default=True),
        ),
    ]
