services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  celery:
    volumes:
      - .:/code

  celery_beat:
    volumes:
      - .:/code

  postgres:
    ports:
      - "5433:5432"

  nginx:
    ports: !override
      - "80:80"
