# Generated by Django 5.2.2 on 2026-08-18 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promocodes', '0003_alter_promoredemptionattempt_failure_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_finalized', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'розыгрыш',
                'verbose_name_plural': 'розыгрыши',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'приз',
                'verbose_name_plural': 'призы',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('determined_manually', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='giveaway.dailydraw')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winners', to='giveaway.prize')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giveaway_wins', to='promocodes.promocode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giveaway_win', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'победитель',
                'verbose_name_plural': 'победители',
                'constraints': [models.UniqueConstraint(fields=('draw', 'prize'), name='one_winner_per_draw_prize')],
            },
        ),
    ]
