# Generated by Django 5.2.2 on 2026-08-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0003_seed_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
