# Generated by Django 5.2.2 on 2026-08-25 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0005_seed_resend_periodic_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='determined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_draws', to=settings.AUTH_USER_MODEL),
        ),
    ]
