# Generated by Django 5.2.2 on 2026-09-17 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("giveaway", "0011_draw_schedule_to_calendar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="winner",
            name="winner_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="email на момент выигрыша",
            ),
        ),
        migrations.AddField(
            model_name="winner",
            name="winner_full_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=300,
                verbose_name="ФИО на момент выигрыша",
            ),
        ),
        migrations.AddField(
            model_name="winner",
            name="winner_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="телефон на момент выигрыша",
            ),
        ),
        migrations.AlterField(
            model_name="winner",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="giveaway_wins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
