# Generated by Django 5.2.2 on 2026-09-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0013_backfill_winner_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='email_send_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='попыток отправки письма'),
        ),
    ]
