# Generated by Django 5.2.2 on 2026-08-17 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoRedemptionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_input', models.CharField(max_length=8)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, choices=[('not_found', 'Код не найден'), ('already_used', 'Код уже использован'), ('banned', 'Временная блокировка'), ('rate_limited', 'Слишком много попыток'), ('profile_incomplete', 'Не заполнен профиль')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'попытка ввода промокода',
                'verbose_name_plural': 'попытки ввода промокода',
            },
        ),
    ]
