# Generated by Django 5.2.2 on 2026-08-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0002_promoredemptionattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoredemptionattempt',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('not_found', 'Код не найден'), ('already_used', 'Код уже использован'), ('banned', 'Временная блокировка'), ('profile_incomplete', 'Не заполнен профиль')], max_length=20),
        ),
    ]
