# Generated by Django 5.2.2 on 2026-08-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0003_alter_promoredemptionattempt_failure_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoredemptionattempt',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('not_found', 'Код не найден'), ('already_used', 'Код уже использован'), ('banned', 'Временная блокировка'), ('profile_incomplete', 'Не заполнен профиль'), ('email_not_confirmed', 'Почта не подтверждена')], max_length=20),
        ),
    ]
