# Generated by Django 5.2.2 on 2026-08-26 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0004_alter_promoredemptionattempt_failure_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['used_at', 'used_by'], name='promo_used_at_by_idx'),
        ),
        migrations.AddIndex(
            model_name='promoredemptionattempt',
            index=models.Index(fields=['created_at', 'success'], name='attempt_created_at_idx'),
        ),
    ]
