# Generated by Django 5.2.2 on 2026-09-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promocodes", "0005_promocode_promo_used_at_by_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promoredemptionattempt",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_found", "Код не найден"),
                    ("already_used", "Код уже использован"),
                    ("banned", "Временная блокировка"),
                    ("profile_incomplete", "Не заполнен профиль"),
                    ("email_not_confirmed", "Почта не подтверждена"),
                    ("campaign_not_started", "Акция ещё не началась"),
                    ("campaign_ended", "Акция завершена"),
                ],
                max_length=20,
            ),
        ),
    ]
