# Generated by Django 5.2.2 on 2026-09-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promocodes", "0007_alter_promoredemptionattempt_failure_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promoredemptionattempt",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_found", "Код не найден"),
                    ("already_used", "Код уже использован"),
                    ("own_code_repeated", "Свой же код введён повторно"),
                    ("banned", "Временная блокировка"),
                    ("profile_incomplete", "Не заполнен профиль"),
                    ("email_not_confirmed", "Почта не подтверждена"),
                    ("campaign_not_started", "Акция ещё не началась"),
                    ("campaign_ended", "Акция завершена"),
                    ("period_transition", "Переход между периодами розыгрыша"),
                ],
                max_length=20,
            ),
        ),
    ]
