# Generated by Django 5.2.2 on 2026-08-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('users_registered', models.PositiveIntegerField(default=0)),
                ('promo_success', models.PositiveIntegerField(default=0)),
                ('promo_failed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'дневная статистика',
                'verbose_name_plural': 'дневная статистика',
                'ordering': ['-date'],
            },
        ),
    ]
